// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportMKV(arg1:string,arg2:Array<main.Chapter>):Promise<Record<string, any>>;

export function LoadMetadata(arg1:string):Promise<Record<string, any>>;

export function SaveMetadata(arg1:Array<main.Chapter>):Promise<Record<string, any>>;
