// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMKV(arg1, arg2) {
  return window['go']['main']['App']['ExportMKV'](arg1, arg2);
}

export function LoadMetadata(arg1) {
  return window['go']['main']['App']['LoadMetadata'](arg1);
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}
